### ISSUE TITLE
Undelivered Mail Returned to Sender

### ISSUE THREAD

**Issue by qdbdbp** [flashmob/go-guerrilla#100]
Undelivered Mail Returned to Sender

`time="2018-02-23T11:58:51Z" level=debug msg="Client sent: MAIL FROM:<>"
time="2018-02-23T11:58:51Z" level=debug msg="Writing response to client: \n250 2.1.0 OK\r\n"
time="2018-02-23T11:58:51Z" level=debug msg="Client sent: RCPT TO:<test@example.com>"
time="2018-02-23T11:58:51Z" level=debug msg="Writing response to client: \n250 2.1.5 OK\r\n"
time="2018-02-23T11:58:51Z" level=debug msg="Client sent: DATA"
time="2018-02-23T11:58:51Z" level=debug msg="Writing response to client: \n503 5.5.1 Error: No sender\r\n"
time="2018-02-23T11:58:51Z" level=debug msg="Client sent: RSET"
time="2018-02-23T11:58:51Z" level=debug msg="Writing response to client: \n250 2.1.0 OK\r\n"
time="2018-02-23T11:58:51Z" level=debug msg="Client sent: QUIT"
time="2018-02-23T11:58:51Z" level=debug msg="Writing response to client: \n221 2.0.0 Bye\r\n"`

**Comment by flashmob** [comment]
Thanks for this!
