### ISSUE TITLE
SMTP Proxy

### ISSUE THREAD

**Issue by bir** [flashmob/go-guerrilla#107]
I'm looking at leveraging go-guerrilla as an SMTP Proxy.  Specifically, an email comes in, we look the address up in an internal database (PG) and then forward to a new address.  Raw performance is not a concern, so running a store and forward could work as well.  At first glance, it does not appear that go-guerrilla has a backend processor that supports this directly.  Would the best solution be to use the DB backend then have a poll that picks off the emails and forwards, rather than trying to introduce the processor with the SMTP flow?

**Comment by flashmob** [comment]
Not sure about that one. Perhaps you could store the emails first, then develop another program that queues them for forwarding. Also, small backend could be developed that checks the recipient address mapping exists, before the email gets saved. When saving, you could also rewrite the headers there, so saved emails would be ready to be queued.

Another idea could be, if you may want to save some dev time and not worried about performance, then Postfix could be an alternative, something like this: https://workaround.org/ispmail/jessie/postfix-mysql
