### ISSUE TITLE
Store file attachment

### ISSUE THREAD

**Issue by kudo28** [flashmob/go-guerrilla#108]
Hi there, I have successfully built a Go-Guerrilla Mail Server on POSIX System. Now I want to store the file attachment from incoming mail. Is there any method to support this? If not , can you suggest me some ways to do so. 
If I use MailDir, I can store all the data from mail , not only the attachment. And the file attachment is like below : 

> --001a1141c082b633a705687449d8
> Content-Type: application/octet-stream; name=testAttachment
> Content-Disposition: attachment; filename=testAttachment
> Content-Transfer-Encoding: base64
> X-Attachment-Id: f_jfaslcne0
> 
> dGhpcyBpcyBhIHRlc3QgYXR0YWNobWVudAoK
> --001a1141c082b633a705687449d8--

I want to store only file attachment. Please suggest me a way.

**Comment by flashmob** [comment]
After storing an email, you'll need to parse it to get the attachments. Perhaps you can use a Mime decoder library, such as https://github.com/jhillyerd/enmime
Or, you could use a utility to get the attachments, some suggested here: https://superuser.com/questions/406125/utility-for-extracting-mime-attachments
