### ISSUE TITLE
It's not displaying email body

### ISSUE THREAD

**Issue by coeqa-dev** [flashmob/go-guerrilla#127]
It's not displaying email body. Please help on this
![image](https://user-images.githubusercontent.com/39934845/49208504-e4240080-f3f2-11e8-9f13-8df76c84a5f9.png)

**Comment by ktanev** [comment]
I notice the issue too. 
![selection_070](https://user-images.githubusercontent.com/5113553/49220707-9356dc80-f3df-11e8-8603-716d72aed4b0.png)

**Comment by akkijadhav123** [comment]
First, I thought it was HTML causing this issue, but it's not that either.

**Comment by flashmob** [comment]
Sorry guys...
Redis on our server was causing the issue. This is because the systemd config file for Redis got reset during an auto-update, that caused Redis to stall.
Restored the config and looks like it's working now.

**Comment by akkijadhav123** [comment]
Thanks ,

Its working perfectly fine now.
