### ISSUE TITLE
Header detection & MIME content aware Reader for the DATA command

### ISSUE THREAD

**Issue by flashmob** [flashmob/go-guerrilla#130]
We can scan for the header boundary as we receive the emails in the DATA command state, saving the position of the header boundary for later processing, and/or parse as we go along. At present, the data is re-scanned at the end of the transaction.

Additionally, once we have the header, we could could have a MIME aware reader, that can read in chunks and is aware about content boundaries, getting us closer to addressing issue #84

**Comment by iwex** [comment]
Hi, I have some problem with headers. Should I start new Issue?

**Comment by iwex** [comment]
`DEBU[0001] Client sent: DATA                            
DEBU[0001] Writing response to client: 
 54 Enter message, ending with '.' on a line by itself
ERRO[0001] parse headers error                           error=EOF`

**Comment by flashmob** [comment]
Hi there. Yes, you can report an issue and include sample input that
triggered the error please.

**Comment by flashmob** [comment]
Fixed in #142
