### ISSUE TITLE
Currently Unable to use guerrilaMail.checkEmail() 

### ISSUE THREAD

**Issue by swnathan** [flashmob/go-guerrilla#132]
Currently Unable to use guerrilaMail.checkEmail() 

Getting below Message 

{"error":"Please call get_email_address or set_email_user first","stats":{"sequence_mail":"55,523,881","created_addresses":38163242,"received_emails":"10,651,382,149","total":"10,595,858,268","total_per_hour":"24249"},"auth":{"success":true,"error_codes":[]}}

**Comment by flashmob** [comment]
Please call get_email_address or set_email_user first
