### ISSUE TITLE
Issue with importing go-guerrilla as a package

### ISSUE THREAD

**Issue by FUSAKLA** [flashmob/go-guerrilla#133]
Hi, I'd like to use go-guerrilla as a package but unfortunately fail to get it working.
I'm using the default example from https://github.com/flashmob/go-guerrilla/wiki/Using-as-a-package

```go
package main
import (
	"fmt"
	"github.com/flashmob/go-guerrilla/guerrilla"
)
func main() {
	d := guerrilla.Daemon{}
	err := d.Start()
	if err == nil {
		fmt.Println("Server Started!")
	}
}
```

But Go fails to find the guerrilla package during build.

The issue is it fails to get the `github.com/flashmob/go-guerrilla/guerrilla` package at all. 
```bash
$ go version
go version go1.11.2 linux/amd64
```
The error is:
```bash
go get github.com/flashmob/go-guerrilla/guerrilla
package github.com/flashmob/go-guerrilla/guerrilla: cannot find package "github.com/flashmob/go-guerrilla/guerrilla" in any of:
	/usr/local/go/src/github.com/flashmob/go-guerrilla/guerrilla (from $GOROOT)
	/go/src/github.com/flashmob/go-guerrilla/guerrilla (from $GOPATH)
```

I tried in docker for golang versions 1.9, 1.10 and 1.11 and neither works.

**Comment by FUSAKLA** [comment]
Hm.. using just `import "github.com/flashmob/go-guerrilla"` works but `go imports` unfortunately auto-completes this by adding the `/guerrilla` to it.

Also might be worth to fix in the docs.

**Comment by flashmob** [comment]
Thanks! Fixed.
