### ISSUE TITLE
INSERT SQL is MySQL specific

### ISSUE THREAD

**Issue by lllama** [flashmob/go-guerrilla#145]
The `INSERT` statement in the SQL backend is specific. In particular, changing the backend to postgres results in SQL error.

The two main changes to make are: 
1. backticks need to be replaced with double quotes
2. `?` placeholders need to be replaced with `$x`, where `x` increments.

I'm not sure whether it's possible to replace the SQL with something more cross-platform or whether there is the need for DB specific backends.

**Comment by flashmob** [comment]
Thanks for the info, didn't know about the backticks and placeholders. You're welcome to attempt to change it to a more cross platform query, then post it here, so it can be tested with MySQL. Also would welcome to suggest any other solutions, eg. recommend an ORM or something similar that's more cross platform.

**Comment by flashmob** [comment]
Another idea would be to refactor `prepareInsertQuery` to allow the SQL query to be configurable via the config?

**Comment by lllama** [comment]
So I have something working in my backend which takes the SQL from the config. I'm marking it as `omitempty`, as I think that would allow a fallback to the MySQL statement. The current implementation requires `sql_insert` and `sql_values` config values as there is a requirement for multiple row inserts. I don't think this is a major issue as it allows for some additional customisation of the SQL but does require two variables to be configured, which has the potential to be confusing.

I'll look to get a pull request done asap.

**Comment by flashmob** [comment]
Thanks for the update, sounds good.

**Comment by lllama** [comment]
The SQL insert statement can now be changed in the config thanks to #157, so I'll close this.

**Comment by lord-alfred** [comment]
In wiki page: https://github.com/flashmob/go-guerrilla/wiki/Configuration-example:-save-to-Redis-&-MySQL

There are incorrect variables for config. Need `sql_insert` and `sql_values`, not `SQLInsert` and `SQLValues`

**Comment by flashmob** [comment]
Thanks. Corrected!

**Comment by liretoy816** [comment]
Replacing backticks with double quotes; was it done, or is it still a to-do?

**Comment by lllama** [comment]
You can now define your own SQL statement in the config. Have a look at the wiki page or pull request linked above
