### ISSUE TITLE
unnecessary conversion

### ISSUE THREAD

**Issue by tegk** [flashmob/go-guerrilla#155]
server.go:544:31:
`client.bufin.setLimit(int64(sc.MaxSize) + 1024000) // This a hard limit.`
			                           
server.go:469:51:
`client.MailFrom, err = client.parsePath([]byte(input[10:]), client.parser.MailFrom)`

**Comment by flashmob** [comment]
Indeed. PR welcome. The 1024000 could be made a constant too.
