### ISSUE TITLE
unpinned variable

### ISSUE THREAD

**Issue by tegk** [flashmob/go-guerrilla#156]
(I still need to verify this bug as this comes from static analysis)

`guerrilla.go:132:30`
Using a reference for the variable on range scope `sc`
`server, err := newServer(&sc, g.backend(), g.mainlog())`

So the value of  "&sc" will be always the same as it unpinned, right?

Fix would be to pin with  `sc := sc`

```
// Instantiate servers
func (g *guerrilla) makeServers() error {
	g.mainlog().Debug("making servers")
	var errs Errors
	for _, sc := range g.Config.Servers {
		if _, ok := g.servers[sc.ListenInterface]; ok {
			// server already instantiated
			continue
		}
		if err := sc.Validate(); err != nil {
			g.mainlog().WithError(errs).Errorf("Failed to create server [%s]", sc.ListenInterface)
			errs = append(errs, err)
			continue
		} else {
			server, err := newServer(&sc, g.backend(), g.mainlog())
			if err != nil {
				g.mainlog().WithError(err).Errorf("Failed to create server [%s]", sc.ListenInterface)
				errs = append(errs, err)
			}
			if server != nil {
				g.servers[sc.ListenInterface] = server
				server.setAllowedHosts(g.Config.AllowedHosts)
			}
		}
	}
	if len(g.servers) == 0 {
		errs = append(errs, errors.New("there are no servers that can start, please check your config"))
	}
	if len(errs) == 0 {
		return nil
	}
	return errs
}
```

**Comment by flashmob** [comment]
Thanks, indeed - the pointer would get clobbered. Should have been using the index instead of value when getting the reference. So change the range so that it also gets the index `i`, then change


newServer(&sc, g.backend(), g.mainlog())

to

newServer(&g.Config.Servers[k], g.backend(), g.mainlog())

Not sure why this hasn't been caught earlier, but nice catch! Do you want to submit the PR?

**Comment by tegk** [comment]
Yes, I will try to fix all the issues I have submitted. Just wanted to discuss with you beforehand.

**Comment by flashmob** [comment]
Hi @tegk eagerly awaiting your PR :-)
Since this issue contains a bug, it has a more significant priority, and would like see this fixed this soon. Thanks.
