### ISSUE TITLE
How much workers need to run?

### ISSUE THREAD

**Issue by lord-alfred** [flashmob/go-guerrilla#161]
I want to test guerrilla on a small VPS with 2 CPU cores. How many maximum workers (`save_workers_size` config) can I run?

As far as I understood: separate processes are launched, and not gorutines - why? If it were gorutine, then in fact it would be possible to process thousands of letters even on weak hardware.

Or do I need to run guerrilla on more powerful hardware? What advise? (I sometimes get 100 thousand letters per night)

**Comment by flashmob** [comment]
No, it's using goroutines.

How many depends on what you decide. You can benchmark your system to see
how many it can handle at once. For a small VPS, probably just one or two
workers.
