### ISSUE TITLE
Need more logging for hande signals from OS

### ISSUE THREAD

**Issue by lord-alfred** [flashmob/go-guerrilla#166]
Signals for reload config and reopen logs need more logging for debug: https://github.com/flashmob/go-guerrilla/blob/3493a860b0beccc0935252dd3a715ed3573dd1c9/cmd/guerrillad/serve.go#L75-L84

Simple case: I configure `deploy-hook` in certbot for reload config in guerrilla, but if hook failed - I can’t find out if the call was successful.

I could send PR if you tell me if I want to change the code correctly:
```go
		if sig == syscall.SIGHUP {
			mainlog.Infof("reload config signal caught")
			if ac, err := readConfig(configPath, pidFile); err == nil {
				_ = d.ReloadConfig(*ac)
				mainlog.Debugf("reload config successful")
			} else {
				mainlog.WithError(err).Error("Could not reload config")
			}
		} else if sig == syscall.SIGUSR1 {
                        mainlog.Infof("reopen logs signal caught")
			if err := d.ReopenLogs(); err != nil {
				mainlog.WithError(err).Error("reopening logs failed")
			} else {
				mainlog.Debugf("reopen logs successful")
			}
		}
```
?

`Infof` + `Debugf ` is good for this or need another methods?

**Comment by flashmob** [comment]
Perhaps see guerrilla.go, there is a section which deals with TLS config changes, around line 320.
It sends a log entry whenever the change passed or failed.

**Comment by lord-alfred** [comment]
Thanks! I did not see this notification in the log.
If, in your opinion, no changes are required, you can close this issue.
