### ISSUE TITLE
Make configurable db.SetMaxOpenConns, db.SetMaxIdleConns and db.SetConnMaxLifetime

### ISSUE THREAD

**Issue by lord-alfred** [flashmob/go-guerrilla#174]
I think it would be useful to be able to change `db.SetMaxOpenConns(X)`, `db.SetMaxIdleConns(Y)` and `db.SetConnMaxLifetime(Z)` in the configuration file. What do you think?

I will first try to do this in my backend, and then I will send PR (if someone does not get ahead of me).

PS: https://www.alexedwards.net/blog/configuring-sqldb
 and http://techblog.en.klab-blogs.com/archives/31093990.html

**Comment by flashmob** [comment]
Is this for the SQL driver? If so, perhaps the same result can already be
configured via the DSN, see all the options here
https://github.com/go-sql-driver/mysql/blob/master/README.md#dsn-data-source-name

**Comment by lord-alfred** [comment]
Yes, for SQL driver. But this driver dont provide DSN options for change this parameters: https://github.com/go-sql-driver/mysql/blob/master/README.md#connection-pool-and-timeouts

And in article on alexedwars blog (link above) says: 

> By default sql.DB allows a maximum of 2 idle connections to be retained in the connection pool. You can change this via the SetMaxIdleConns() method

**Comment by flashmob** [comment]
All right, can be a config option then. PR welcome.

**Comment by lord-alfred** [comment]
Don’t forget to add info to the wiki :)
I do not close issue so that there is a reminder of this. Close it yourself later.

**Comment by flashmob** [comment]
Wiki updated.
