### ISSUE TITLE
Cannot refer to unexported name backends.compressor

### ISSUE THREAD

**Issue by bsord** [flashmob/go-guerrilla#190]
**What I'm trying to do:**
Customize the Redis and MySQL backends by copying them and importing them a different package while using guerrilla as a module.

**Problem:**
Error 'cannot refer to unexported name backends.compressor' is received when attempting to use compressor outside of the 'backends' package because the definition of the struct in backends/p_compressor.go is lower case, thus non-exportable. It looks like the 'capital' version of compressor is used to export the function used by the processor chain so cannot simply capitalize.

**Solution:**
Rename the compressor struct definition in p_compressor.go to DataCompressor (as well as update the built-in Redis and MySQL backend references) so it can be used by other packages.

**Comment by flashmob** [comment]
Sounds good, please feel free to submit a PR

**Comment by bsord** [comment]
PR submitted. Let me know if there are any concerns. https://github.com/flashmob/go-guerrilla/pull/191

**Comment by flashmob** [comment]
Merged, thank you!

**Comment by bsord** [comment]
Forgot to expose the attributes of the struct as well :D

PR incoming

**Comment by bsord** [comment]
https://github.com/flashmob/go-guerrilla/pull/192 submitted to also expose the attributes of the struct as well.

**Comment by bsord** [comment]
Confirmed resolved after second PR. Thanks again for quick responses.
