### ISSUE TITLE
The “header” processor populates “Received:” headers wrongly.

### ISSUE THREAD

**Issue by issuefiler** [flashmob/go-guerrilla#198]
## [RFC 5321](https://tools.ietf.org/html/rfc5321#section-4.4)

```
   From-domain    = "FROM" FWS Extended-Domain

   By-domain      = CFWS "BY" FWS Extended-Domain

   Extended-Domain  = Domain /
                    ( Domain FWS "(" TCP-info ")" ) /
                    ( address-literal FWS "(" TCP-info ")" )

   TCP-info       = address-literal / ( Domain FWS address-literal )
                  ; Information derived by server from TCP connection
                  ; not client EHLO.
```

-----

https://github.com/flashmob/go-guerrilla/blob/51f7dda326b1e9878e5f679ccb34a134127951b0/backends/p_header.go#L59

A  `Domain` in a `TCP-info` should not be from the `HELO` command. Would better omit it as `go-guerrilla` doesn’t do rDNS lookup.

 And replacing `from` with `FROM` would better comply with the RFC. (Unsure if case-insensitive.)

-----

https://github.com/flashmob/go-guerrilla/blob/51f7dda326b1e9878e5f679ccb34a134127951b0/backends/p_header.go#L61

 I can’t say it is wrong for this one, just want to know your opinion on changing `with SMTP` to [`WITH ESMTPS`](https://www.iana.org/assignments/mail-parameters/mail-parameters.xhtml#mail-parameters-7), as `go-guerrilla` supports both `EHLO` and `STARTTLS` (which might be a poor reason to back it).

**Comment by flashmob** [comment]
Hi, thanks for the bug reports - they're excellently written!
Sorry, no time to respond them yet, will soon.
Also, is there a way to contact you directly via email? If so, please submit a ticket to https://guerrillamail.uservoice.com/

**Comment by flashmob** [comment]
Thanks.

TODO

* Remove e.Helo from the tcp-info header, only include the source IP in the tcp info
* Change `with SMTP` to `with ESMTPS' / `with ESMTP`, depending on what protocol was used

As for, FROM - in the wild, eg. Postfix, Gmail always leave it all lowercase.

**Comment by flashmob** [comment]
Implimented in #202

* Remove e.Helo from the tcp-info header, only include the source IP in the tcp info
* Change with `SMTP` to with `ESMTPS' / `with ESMTP`, depending on what protocol was used
