### ISSUE TITLE
[FR] Download Email as .eml format

### ISSUE THREAD

**Issue by fazlerabbi37** [flashmob/go-guerrilla#208]
It is very exciting to see a disposable mail service based on open source technology. I am using it for sometime and would like to request a feature. It would be a great help if we could download the emails as [.eml](https://en.wikipedia.org/wiki/Email#Filename_extensions) format as the mail box is cleaned after 24 hours. 

Thanks for the great application!

**Comment by flashmob** [comment]
Thanks for the feedback. This suggestion will be passed down to the Guerrilla Mail admin.
