### ISSUE TITLE
Scary Enough for Halloween Contest

### ISSUE THREAD

**Issue by batara666** [flashmob/go-guerrilla#219]
![https://raw.githubusercontent.com/flashmob/go-guerrilla/master/GoGuerrilla.png](https://raw.githubusercontent.com/flashmob/go-guerrilla/master/GoGuerrilla.png)![https://raw.githubusercontent.com/flashmob/go-guerrilla/master/GoGuerrilla.png](https://raw.githubusercontent.com/flashmob/go-guerrilla/master/GoGuerrilla.png)![https://raw.githubusercontent.com/flashmob/go-guerrilla/master/GoGuerrilla.png](https://raw.githubusercontent.com/flashmob/go-guerrilla/master/GoGuerrilla.png)![https://raw.githubusercontent.com/flashmob/go-guerrilla/master/GoGuerrilla.png](https://raw.githubusercontent.com/flashmob/go-guerrilla/master/GoGuerrilla.png)![https://raw.githubusercontent.com/flashmob/go-guerrilla/master/GoGuerrilla.png](https://raw.githubusercontent.com/flashmob/go-guerrilla/master/GoGuerrilla.png)![https://raw.githubusercontent.com/flashmob/go-guerrilla/master/GoGuerrilla.png](https://raw.githubusercontent.com/flashmob/go-guerrilla/master/GoGuerrilla.png)

**Comment by flashmob** [comment]
😁
