### ISSUE TITLE
How do I build/run this?

### ISSUE THREAD

**Issue by dvcrn** [flashmob/go-guerrilla#22]
Apologies for the naive question. I am currently investigating different SMTP servers for receiving email  and this one caught my attention (wanting to build that project in Go). 

I seem to have problems figuring out how to get started with this project. 

```
To build, just run

$ go build

(...)
```

This information is a little bit unclear. Running build from the root doesn't seem to do much. How were I to go specifically from checking this project out to actually running it? 

Any hint in the right direction would be greatly appreciated!

**Comment by flashmob** [comment]
Hi, thanks for checking it out!

Currently, to build the latest master you will need to use the "GNU make" tool and the latest Go compiler.
`$ make guerrillad` will build a binary named guerrillad, which you can execute. 
What platform do you want to build on?

**Comment by dvcrn** [comment]
Ah I did not see the Makefile somehow, whoops! Thanks for the speedy answer, all good now 😊
