### ISSUE TITLE
AWS S3 Backend

### ISSUE THREAD

**Issue by simonmacklin** [flashmob/go-guerrilla#228]
Hi 

Thanks for this great package!  I would like to write a new processor to push each email to s3.  This would be to mimic the AWS SES to S3 feature.

Do you see any issues using this package and a S3 processor?  

If no would you me to create a PR for the processor to be part of this package?

Thanks

Simon

**Comment by phires** [comment]
Issue is now tracked in new repo: https://github.com/phires/go-guerrilla/issues/25
