### ISSUE TITLE
GuerrilaMail doesn't send email

### ISSUE THREAD

**Issue by DiabloStorm** [flashmob/go-guerrilla#234]
Tested with 2 other temp email inboxes, guerrillamail sends nothing but acts like it does. Made sure receiving inboxes work. Issue is guerrillamail

**Comment by dizys** [comment]
It says in the README:

> The purpose of this daemon is to grab the email, save it, and disconnect as quickly as possible, essentially performing the services of a Mail Transfer Agent (MTA) **without the sending functionality**.

This is probably not it if you're looking for a fully-fledged SMTP server.

**Comment by DiabloStorm** [comment]
Okay, if it was intended to only receive email, the entire "compose" tab for sending email is entirely pointless and misleading. My bad for not checking the readme. It's the equivalent of having a button that says what it does, but hidden in the details of the manual, says that button does nothing.

**Comment by phires** [comment]
This is the software behind GuerillaMail, but my guess is that it is abandoned by it's owner as is this repo.
