### ISSUE TITLE
is this project abandoned?

### ISSUE THREAD

**Issue by amarjeetanandsingh** [flashmob/go-guerrilla#236]

**Comment by phires** [comment]
Hi, I am one of the original contributors of the project.
The owner has abandoned it as far as I can tell. 
I will check, if I can still push to the Repo to get the most pressing issues resolved and maybe move the whole project over for further development.

**Comment by amarjeetanandsingh** [comment]
We have any future development roadmaps?

**Comment by phires** [comment]
Let me get an overview of the current state, I was not working on the project for some while.
I guess first steps will be to get it up to speed with the current go version and modules.

**Comment by phires** [comment]
Project now lives on under https://github.com/phires/go-guerrilla.
