### ISSUE TITLE
Is the project and bounties still active?

### ISSUE THREAD

**Issue by akandle** [flashmob/go-guerrilla#239]
I was hoping to take a stab at increasing test coverage and hopefully nabbing some bounty along the way.

Before I go through the work of setting up coverage tests, I was wondering to what extent the project is still going and viable.  Obviously the website is still running and working for the most part as intended, and for that I do want to commend the contributors so far, as it would seem that even though it has been 2 years since the last update, the site is still humming along.

I very well may just go through with the test coverage setup and then start shoring up missing tests. To that point, I want to contribute to this project rather than strictly my own fork, and so hopefully this project is simply getting a little dusty rather than having been abandoned.

And regarding the possibility the project is no longer able to be maintained, what are the chances of passing the reigns to a new maintainer or allowing some assistance in that respect?  I don't care too much personally about being in charge of the hosting and maintaining the live site as it is, but I would be interested in at least assisting the maintenance of the repository and code base, at least to ensure that necessary security patches and upgrades are applied, and to test and approve any pull requests from the community.

I hope the maintainer is well and in good health, and would love to help out instead of this wonderful project dying a slow death.

Also to add, I am no expert in email infrastructure or even this project.  I am a user of the service and happened to notice it was open source, and so here I am.

Best Regards,
Aaron

**Comment by akandle** [comment]
Hello,

Let me know what you are thinking about and we can see what we can do.  Do
you have any idea of what exactly you would like to implement or is it just
bug fixing and keeping the system all current.

Thanks,
Aaron

**Comment by morelmiles** [comment]
Hi @codeline-ae, 
Could we talk about the bug fixing and your needs? 

Cheers,
Morel

**Comment by phires** [comment]
Hi, I am one of the original contributors of the project.
The owner has abandoned it as far as I can tell. 
I will check, if I can still push to the Repo to get the most pressing issues resolved and maybe move the whole project over for further development.

**Comment by phires** [comment]
Project now lives on under https://github.com/phires/go-guerrilla.
