### ISSUE TITLE
guerrillamail duplicates a dot character when the dot appears at index 76

### ISSUE THREAD

**Issue by kilaka** [flashmob/go-guerrilla#24]
Example:
Send email from anywhere to guerrillamail with the following text:
123456789012345678901234567890123456789012345678901234567890123456789012345.com
Result in `Show original`:
123456789012345678901234567890123456789012345678901234567890123456789012345=
..com
guerrillamail duplicates the dot.
This causes links to be broken.
Good luck :)

**Comment by flashmob** [comment]
Thanks. Fixed the code now, will deploy on Guerrilla Mail soon.
