### ISSUE TITLE
Support enhanced status codes

### ISSUE THREAD

**Issue by flashmob** [flashmob/go-guerrilla#34]
RFC https://tools.ietf.org/html/rfc3463

https://www.iana.org/assignments/smtp-enhanced-status-codes/smtp-enhanced-status-codes.xml

1. Implement enhanced status codes to all status messages

2. Advertise 250-ENHANCEDSTATUSCODES after EHLO

3. Automated tests for all codes

**Comment by dapaxx** [comment]
I am looking into this if it is still open

**Comment by flashmob** [comment]
Hi,
Thanks your interest. Yes, it's still open!
Would be glad to assign this to you. Do you have an idea how you would tackle this?
Also, this is not part of the reward bounties, however, if you include the tests then it will be eligible for the test coverage bounty,
