### ISSUE TITLE
doc: Document AppConfig / ServerConfig

### ISSUE THREAD

**Issue by ginkoob** [flashmob/go-guerrilla#57]
I'm looking to implement LetsEncrypt but I've got stuck on basic understanding of the code due the lack of documentation. What is ``AppConfig.AllowedHosts`` and how is it related to ``ServerConfig.Hostname`` ?

**Comment by flashmob** [comment]
`AppConfig.AllowedHosts` controls which hosts the "RCPT TO" command will accept.
`ServerConfig.Hostname` is what gets displayed in the 250 reply to HELO/EHLO
