### ISSUE TITLE
What's the license for this repo?

### ISSUE THREAD

**Issue by oliverjanik** [flashmob/go-guerrilla#6]
Can I fork, modify and run on my systems?

**Comment by xyproto** [comment]
It's the MIT license.

Source: Google the text at the top of [goguerrilla.go](https://github.com/flashmob/go-guerrilla/blob/master/goguerrilla.go) to find the [MIT license](https://www.google.no/search?client=safari&rls=en&q=is+hereby+granted,+free+of+charge,+to+any+person+obtaining+a+copy+of+this+software+and+associated+documentation+files+(the+%22Software%22),+to+deal+in+the+Software+without+restriction,+including+without+limitation+therights+to+use,+copy,+modify,+merge,+publish,+distribute,+sublicense,+and/or+sell+copies+of+the+Software,+and+topermit+persons+to+whom+the+Software+is+furnished+to+do+so,+subject+to+the+following+conditions:The+above+copyright+notice+and+this+permission+notice+shall+be+included+in+all+copies+or+substantial+portions+of+theSoftware.THE+SOFTWARE+IS+PROVIDED+%22AS+IS%22,+WITHOUT+WARRANTY+OF+ANY+KIND,+EXPRESS+OR+IMPLIED,+INCLUDING+BUT+NOT+LIMITED+TO+THEWARRANTIES+OF+MERCHANTABILITY,+FITNESS+FOR+A+PARTICULAR+PURPOSE+AND+NONINFRINGEMENT.+IN+NO+EVENT+SHALL+THE+AUTHORS+ORCOPYRIGHT+HOLDERS+BE+LIABLE+FOR+ANY+CLAIM,+DAMAGES+OR+OTHER+LIABILITY,+WHETHER+IN+AN+ACTION+OF+CONTRACT,+TORT+OROTHERWISE,+ARISING+FROM,+OUT+OF+OR+IN+CONNECTION+WITH+THE+SOFTWARE+OR+THE+USE+OR+OTHER+DEALINGS+IN+THE+SOFTWARE.&ie=UTF-8&oe=UTF-8&gfe_rd=cr).
