### ISSUE TITLE
backends: Backend interface should not have private methods

### ISSUE THREAD

**Issue by ginkoob** [flashmob/go-guerrilla#60]
Why does Backend has private methods?  https://github.com/flashmob/go-guerrilla/blob/9d9d8645678e8fda93ceb5fceda577d413dfbef8/backends/backend.go#L20

The readme file mentions that different backends can be implemented but it doesn't seem to be the case because you can't use unexported types. It is misleading at best for several reasons:
  - Currently it's impossible to implement the Backend interface due the private methods
  - type Envelope is in the envelope package so in the example it should be ``c *envelope.Envelope`` not ``c *guerrilla.Envelope``.  type BackendResult is located in the backends package so it should be ``backends.BackendResult`` not  ``guerrilla.BackendResult`` 
```
type CustomBackend struct {...}

func (cb *CustomBackend) Process(c *guerrilla.Envelope) guerrilla.BackendResult {
  err := saveSomewhere(c.Data)
  if err != nil {
    return guerrilla.NewBackendResult(fmt.Sprintf("554 Error: %s", err.Error()))
  }
  return guerrilla.NewBackendResult("250 OK")
}
```

An exported interface with private methods makes no sense, does it?

**Comment by flashmob** [comment]
Thanks for that. Yes, it's a mistake.
Thanks for your other feedback too.
Would be glad if you could do some more code review and report your suggestions. Also, welcome to submit a PR with fixes for the backend.
Would gladly award the 0.25 bounty for more complete code review too.

**Comment by flashmob** [comment]
Currently working on refactoring the backends.

 Created a test project that uses go-guerrilla as a package to get a better insigt https://github.com/flashmob/maildiranasaurus

**Comment by eliezedeck** [comment]
Right now, the README and the codes in the `master` branch is out of sync.

What's the state of the refactoring now?

**Comment by flashmob** [comment]
Backend refactoring completed, PR #71 merged
