### ISSUE TITLE
Add an Easter Egg

### ISSUE THREAD

**Issue by flashmob** [flashmob/go-guerrilla#64]
What software is complete without an easter egg?

The HELP command would be a great candidate for an easter egg, since this command is mostly unused and disabled on many other servers.

Todo:

HELP command to reply with random one line quotes from the Big Lebowski
https://www.rottentomatoes.com/m/big_lebowski/quotes/

The Dude abides.

**Comment by dapaxx** [comment]
And here we are. Also multiline quotes - shouldn't matter for the HELP command, which may have multiline

**Comment by flashmob** [comment]
Thanks. These quotes really tie the server together!

On second thought, and I hope that this is not "un-dude", but maybe we could tone down on the profanity - just  to make it Safe For Work (SFW) and not trip any silly filters ;-)
