### ISSUE TITLE
latest go-guerrilla doesn't compile 

### ISSUE THREAD

**Issue by mrcpvn** [flashmob/go-guerrilla#75]
Hello, I tried to go get the latest changes but go install is failing.
flashmob/go-guerrilla/event.go:78: cannot use EventBus.New() (type EventBus.Bus) as type *EventBus.EventBus in assignment: need type assertion

I noticed that the package github.com/asaskevich/EventBus has been changed 6 days ago and created a problem with the compilation of go-guerrilla.
https://github.com/asaskevich/EventBus/commit/5666508a36b5a5347eb4420d52b5e4c4368c8235

**Comment by flashmob** [comment]
Oops.
Please try with glide
It's currently locked to the following revision:
ab9e5ceb2cc1ca6f36a5813c928c534e837681c2
You could also clone event bus and checkout that revision.
