### ISSUE TITLE
Feature request: usage of queues

### ISSUE THREAD

**Issue by lifeofguenter** [flashmob/go-guerrilla#8]
It would be cool if instead of using a mix of redis/mysql it would use a queue (rabbit/beanstalkd/maybe even sqs) to push new messages into (might not work with large attachments though).

That way the implementation of what is being done with a email is fully seperated from the mx.

**Comment by flashmob** [comment]
Thanks. The roadmap is to convert go-guerrilla to a library/module, so you can add rabbit or whatever else when you define your own saveMail function.
Internally, go-guerrilla uses a worker queue for saving email. There are 3 workers by default.
