### ISSUE TITLE
Support Prometheus by exporting metrics through `/metrics` endpoint

### ISSUE THREAD

**Issue by kevinjqiu** [flashmob/go-guerrilla#86]
The Prometheus stack ([Prometheus](https://prometheus.io) + [Grafana](https://grafana.com)) can be used to provide slick, powerful and flexible dashboards. All the project needs to do is to export metrics through an endpoint (e.g., `/metrics`) and let Prometheus scrape it. Prometheus has a powerful data model and query language (PromQL).

**Comment by FUSAKLA** [comment]
Hi, just out of curiosity why was the suggestion shut down? Or what are other oportunitties to monithor go-guerilla?

**Comment by flashmob** [comment]
The Dashboard project has been  completed. It logs the metrics, so in theory any program can also get this data by scraping the logs, no need to provide any new endpoints.
Another reason is that this software is increasingly used as a package by other software, so want to keep the dependency footprint frozen for now
