### ISSUE TITLE
case-insensitive import collision in logrus

### ISSUE THREAD

**Issue by ganglio** [flashmob/go-guerrilla#87]
When importing as a package in an application already using logrus upon compilation it returns the following error:

```
src/github.com/flashmob/go-guerrilla/log/hook.go:5:2: case-insensitive import collision: "github.com/Sirupsen/logrus" and "github.com/sirupsen/logrus"
```

The current logrus readme reports the change in case for the github user asking the update of the package name whenever used to match the new lowercase one.

Could you please update?

**Comment by flashmob** [comment]
Hi,

Thanks for reporting.

The `go get` way to download the dependencies may be broken, especially when the dependencies change, such as the case with logrus. So perhaps you may want to try using the glide tool instead. Glide currently locks logrus to the following commit hash: `ba1b36c82c5e05c4f912a88eab0dcd91a171688f`

Although it would be good to update to the latest logrus soon, so let this issue be a placeholder for the update.

**Comment by ganglio** [comment]
If you want I can fork it and do the case switching. I will need to do it anyway as I really need the package (it’s the most comprehensive and versatile SMTP server as a library out there 😀 ). I could do a pull request if you like.

**Comment by flashmob** [comment]
yes please - would be very welcome. Would this also update the glide dependency?

**Comment by ganglio** [comment]
Sure. Why not 😀 Not sure if I can make it during the weekend, tho. Monday more likely.
