### ISSUE TITLE
Please, don't suggest rotten ssl verions

### ISSUE THREAD

**Issue by athoune** [flashmob/go-guerrilla#9]
> ```
>         ssl_protocols  SSLv2 SSLv3 TLSv1;
> ```

SSLv2 doesn't  exist anymore, and sslv3 is rotten.

**Comment by flashmob** [comment]
Thanks for pointing it out. The server was written in 2011 where majority of ssl connections were using ssllv3 and still a lot of sslv2. So back then, you either allow these, or scratch your head as to why your email is not arriving.
Anyhow, a pull request would be welcome...
