### ISSUE TITLE
Guide on how to setup for production usage

### ISSUE THREAD

**Issue by montanaflynn** [flashmob/go-guerrilla#90]
Hello and thanks for the great software. I am trying to set this up on a server but am unsure on how to actually make emails sent be received. I'm assuming I need to set up DNS but have no experience with setting up email server DNS. It would be helpful if the documentation or wiki had a section for setting up the domain / DNS.

**Comment by flashmob** [comment]
https://github.com/flashmob/go-guerrilla/wiki/Deploying-(POSIX-system)

**Comment by montanaflynn** [comment]
Thanks! The link is broken but I found it in the wiki:

https://github.com/flashmob/go-guerrilla/wiki/Deploying-(on-a-POSIX-system)
