### ISSUE TITLE
 make test  undefined: Iconv

### ISSUE THREAD

**Issue by goodforever** [flashmob/go-guerrilla#91]
Dear all,
   I make test ,then I got 
go test -v .
# gopkg.in/iconv.v1
../../../gopkg.in/iconv.v1/reader.go:10: undefined: Iconv
FAIL	github.com/flashmob/go-guerrilla [build failed]
make: *** [test] Error 2

**Comment by flashmob** [comment]
Sorry for late reply. Recently updated the project to make iconv optional, more info in the build notes https://github.com/flashmob/go-guerrilla/wiki/Build-Notes
