### ISSUE TITLE
Mail forwarding

### ISSUE THREAD

**Issue by pjebs** [flashmob/go-guerrilla#93]
I was looking at this package and I was unclear if I could make a mail forwarder using it.

My aim is to make to have a database that maps 1 email address to another based on a database table.
eg.
A@X.com (alias) => C@D.com (real email address)
E@X.com (alias) => P@Q.com (real email address)

When the incoming mail gets received and then forwarded to the real email address, the real email address should ideally not realise that the email was forwarded. When they click reply for example, it should reply to the original sender.

I tried to implement it using https://github.com/haraka/Haraka but services like hotmail and gmail recognised that a email forwarding was happening and rejected the forwarded email.

According to: https://github.com/haraka/Haraka/issues/1318#issuecomment-177661819 ,  I must use SRS (sender rewriting scheme) for forwarding.

Does go-guerrilla support SRS: https://en.wikipedia.org/wiki/Sender_Rewriting_Scheme?

**Comment by flashmob** [comment]
Sorry for the late reply, unfortunately unable to help as forwarding email is out of scope for this project. This is only for receiving.
